service: test-service-1

provider:
  name: aws
  runtime: nodejs4.3
  stage: ${file(./serverless.env.yml):stage}
  region: ${file(./serverless.env.yml):region}
  credentials:
    accessKeyId: ${file(./serverless.env.yml):accessKeyId}
    secretAccessKey: ${file(./serverless.env.yml):secretAccessKey}

package:
  individually: true

plugins:
  - serverless-scriptable-plugin

custom: 
  scriptHooks:
    before:deploy:function:deploy: "deployment_hooks/before_deploy_function.js"
    after:deploy:function:deploy: "deployment_hooks/after_deploy_function.js"
    before:deploy:createDeploymentArtifacts: "deployment_hooks/before_deploy_create_deployment_artifacts.js"
    after:deploy:createDeploymentArtifacts: "deployment_hooks/after_deploy_create_deployment_artifacts.js"

functions:
  basic:
    handler: functions/basic/handler.foo
    package:
      exclude:
        - "!functions/basic/**/*"
    events:
      - http:
          path: basic
          method: get

  basicWithDeps:
    handler: functions/basic-with-deps/handler.bar
    package:
      exclude:
        - "!functions/basic-with-deps/**/*"
    events:
      - http:
          path: basic-with-deps
          method: get

  buildWithInternalDevDeps:
    handler: functions/build-with-internal-dev-deps/handler.buildExample
    package:
      exclude:
        - "!functions/build-with-internal-dev-deps/**/*"
    events:
      - http:
          path: build-with-internal-dev-deps
          method: get

  buildWithExternalDevDeps:
    handler: functions/build-with-external-dev-deps/handler.buildExample
    package:
      exclude:
        - "!functions/build-with-external-dev-deps/**/*"
    events:
      - http:
          path: build-with-external-dev-deps
          method: get
    
